### ISSUE TITLE
Version 1.0.1 Release Checklist

### ISSUE THREAD

**Issue by jatinchowdhury18** [Chowdhury-DSP/BYOD#139]
- [x] Close out outstanding issues
- [x] Bump version number
- [x] Generate AAX builds
- [x] Test on Windows:
  - [x] Ableton
  - [x] Reaper
  - [x] Pro Tools
- [x] Test on Mac:
  - [x] Ableton
  - [x] GarageBand
  - [x] Logic (M1)
  - [x] Pro Tools
- [x] Test on iOS:
  - [x] AUM
  - [x] GarageBand
- [x] Submit iOS build for review
- [x] Generate release builds/installers
- [x] Release iOS version
- [x] Update documentation:
  - [x] Update README, CHANGELOG, etc
- [x] Tag GitHub Release
- [x] Update website
  - [x] Update build links
